### ISSUE TITLE
Validate that modification of the "anchor" attribute does not affect xml2rfc behavior

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ietf#177]
The BibXML Service is now online and the API allows generation of custom anchors. The old anchors are provided in the legacy data set.

This task is to test Metanorma's generation of RFC XML that uses custom anchors.

**Comment by ronaldtse** [comment]
All that we need is to use Metanorma to generate an RFC XML, then manually change an anchor in definition and usage. And check that xml2rfc processes it properly.

**Comment by ronaldtse** [comment]
It is likely that we cannot use the ENTITY style, because xml2rfc will auto-fetch from xml2rfc.tools.ietf.org, which contains the old hardcoded anchor.

The usage of ENTITY is why the anchor is tied and cannot be unbound. Therefore, we must not use ENTITY for this to work.
i.e. the MN generated RFC XML should not trigger reference auto-fetching by xml2rfc.

**Comment by opoudjis** [comment]
It turns out that you have already disabled the anchors, by suppressing the generation of `/bibitem/uri[@type = 'xml']`. If there is no URI being supplied that points to the xml2rfc.tools.ietf.org repository, so that xi:include can retrieve the XML from it, then no xi:include is going to be generated to begin with. With updated xml2rfc, documents are being generated.

**Comment by opoudjis** [comment]
Confirmed that removing `rfc_anchor_cleanup()` (which updated bibliographic anchor to supplied scope identifier) does not impact generating xml2rfc.
