### ISSUE TITLE
Cross-reference uses title instead of bibliographic entry

### ISSUE THREAD

**Issue by petithug** [metanorma/metanorma-ietf#80]
So I have both a bibliographic item with "AsciiDoc" id (I use bibitem in a metanorma passthrough) and a section whose title is also "AsciiDoc".

When I insert a crossreference (using << >>), it is resolved as a the section instead of the bibliographic item.

**Comment by opoudjis** [comment]
... If for whatever reason there is a bibitem and a clause with an identical identifier, that is a markup fail, and it would be preferable to simply abort execution. We cannot assume that bibitems takes priority over clauses for cross-referencing, or vice versa.

That said, a clause `== AsciiDoc` should be getting an id of `_asciidoc`, not `asciidoc`, and should not be causing a clash. Can you provide an example document, so I can work out what is happening?

**Comment by petithug** [comment]
Here's a minimal example extracted from my work document.  I use `metanorma -t ietf -x txt test.adoc` to generate the text document.  The two references in the "Overview Of Operations" section then point to the same element.

```
= The Computerate Specifying Paradigm
:doctype: internet-draft
:name: draft-petithuguenin-computerate-specifying-pre6-04
:docnumber: draft-petithuguenin-computerate-specifying-pre6-04
:ipr: trust200902
:submission-type: IETF
:abbrev: Computerate Specifying
:status: experimental
:area: General
:intended-series: exp
//:revdate: 2019-11-04T00:00:00Z
:fullname: Marc Petit-Huguenin
:lastname: Petit-Huguenin
:initials: M.
:affiliation: Impedance Mismatch LLC
:email: marc@petit-huguenin.org
:no-isobib:
:local-cache-only:
:toc-depth: 4

:sectnums:

[#overview]
== Overview of Operations

The code in a computerate specification uses the programming language <<Idris2>> in literate programming mode using the Bird-style, by having each line of code starting with a ">" mark in the first column.

The idris2 tool is described in <<cli_idris2>>.

[bibliography]
== Informative References

++++
<bibitem id="Idris2" type="standard">
  <title format="text/plain" language="en" script="Latn">Idris: A Language with Dependent Types</title>
  <uri type="src">https://idris2.readthedocs.io/en/latest/</uri>
  <docidentifier type="">Idris2</docidentifier>
  <contributor>
    <person>
      <name><completename></completename></name>
      <affiliation><organization><name>A</name></organization></affiliation>
    </person>
  </contributor>
</bibitem>
++++

[#cli]
[appendix]
== Command Line Tools

[#cli_idris2]
==== Idris2

[spacing=compact]
URL: :: https://github.com/idris-lang/Idris2.git
Version: :: 0.2.0 commit 143d2
```

**Comment by ronaldtse** [comment]
There are actually two problems here.

1. This block is passthrough'ed to the target format (i.e. Metanorma XML). But since this is passthrough, the Metanorma engine has no understanding of the id `Idris2` until the rendering phase.

```
++++
<bibitem id="Idris2" type="standard">
  <title format="text/plain" language="en" script="Latn">Idris: A Language with Dependent Types</title>
  <uri type="src">https://idris2.readthedocs.io/en/latest/</uri>
  <docidentifier type="">Idris2</docidentifier>
  <contributor>
    <person>
      <name><completename></completename></name>
      <affiliation><organization><name>A</name></organization></affiliation>
    </person>
  </contributor>
</bibitem>
++++
```

2. We rely on Asciidoctor to parse AsciiDoc. Since the anchor of `<<Idris2>>` cannot be resolved in the compilation stage, Asciidoctor somehow has code to "guess" the correct section title. It sees that "Idris2" is a section title, and takes that as the resolved anchor.

Unfortunately we can't bypass this Asciidoctor behavior here. Could you work around this with a different anchor name?

If you use AsciiBib, I believe you can define a different "anchor name" (for processing) vs the "tag name" (the reference tag) of a bib item.

**Comment by opoudjis** [comment]
This is a case falling afoul of the asciidoctor parser; https://github.com/asciidoctor/asciidoctor/blob/5845c665c8f8eec0c95154b00adc32c383fc4efc/lib/asciidoctor/substitutors.rb, line 819:

You are parsing a cross-reference which, as far as the Asciidoctor parser is concerned, does not exist: Asciidoctor cannot read pass-throughs. Normally, Asciidoctor will leave such a hanging cross-reference alone; the cross-reference will be resolved in the Metanorma XML output generated, when the pass-through goes through.

However, you have triggered a special case:

````
 elsif ((fragment.include? ' ') || fragment.downcase != fragment) && (refid = doc.resolve_id fragment)
  fragment, target = refid, %(##{refid})
````

Your cross-reference "Idris" contains a capital letter or a space. This makes asciidoctor assume that it is a typo for a normalised, lowercase cross-reference. It then goes looking for a matching anchor that it can see in the asciidoctor document (`doc.resolve_id fragment`). Since "Idris2" is turning up as a title in the document, it assumes that is what you meant to use, and uses that instead.

I'm afraid you will have to work around this: I cannot override the asciidoctor parser code. If you use pass-through to enter citations, either use only lowercase identifiers for your pass-through  bibitems, or else do *not* use titles of sections identical to pass-through bibitem IDs.

**Comment by petithug** [comment]
All right, I plan to convert the references as AsciiBib as soon the relaton cli permits to retrieve them in that form.  Meanwhile I'll continue to work around that issue.

Thanks.

**Comment by ronaldtse** [comment]
@petithug I think we already have a way of converting between AsciiBib and Relaton XML via Relaton CLI. @andrew2net is this true?

**Comment by andrew2net** [comment]
@ronaldtse I sorry but I didn't have a chance to implement AsciiBib feature. There were a lot of other urgent tasks.

**Comment by petithug** [comment]
So I converted my bibliography to AsciiBib, but I still have the same issue.  See test file below, where the two cross-reference resolve to the same anchor, although they should not:

```
= The Computerate Specifying Paradigm
:doctype: internet-draft
:name: test-title
:docnumber: test-title
:ipr: trust200902
:submission-type: IETF
:abbrev: Computerate Specifying
:status: experimental
:area: General
:intended-series: exp
//:revdate: 2019-11-04T00:00:00Z
:fullname: Marc Petit-Huguenin
:lastname: Petit-Huguenin
:initials: M.
:affiliation: Impedance Mismatch LLC
:email: marc@petit-huguenin.org
:no-isobib:
:local-cache-only:
:toc-depth: 4

:sectnums:

[#overview]
== Overview of Operations

The code in a computerate specification uses the programming language <<Idris2>> in literate programming mode using the Bird-style, by having each line of code starting with a ">" mark in the first column.

The idris2 tool is described in <<cli_idris2>>.

[bibliography]
== Informative References

[%bibitem]
=== {blank}
id:: Idris2
title.type:: main
title.content:: Idris2: A Language with Dependent Types
title.format:: text/plain
type:: standard
date.type:: accessed
date.on:: 2020-08-20
link.type:: src
link.content:: https://idris2.readthedocs.io/en/latest/

[#cli]
[appendix]
== Command Line Tools

[#cli_idris2]
==== Idris2

[spacing=compact]
URL: :: https://github.com/idris-lang/Idris2.git
Version: :: 0.2.0 commit 143d2
```

**Comment by opoudjis** [comment]
Two things: Asciidoctor will continue not parsing the crossreferences properly, so long as it does not see an actual Asciidoctor anchor "Idris2" in the asciidoctor source. So instead of

````
[%bibitem]
=== {blank}
id:: Idris2
````

you will need to use the variant

````
[#Idris2]
[%bibitem]
=== {blank}
````

I am adding that variant to documentation.

Second, there is a bug preventing that from working, which I've just fixed, but you will need to wait for the next release (2 weeks) to see it behaving properly.

**Comment by petithug** [comment]
I confirm that this issue is now fixed.
